# Generated by Django 4.2 on 2023-04-08 10:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyRegisterForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('businessName', models.CharField(max_length=200, null=True)),
                ('mobile', models.CharField(blank=True, default='', max_length=15)),
                ('phone', models.CharField(blank=True, default='', max_length=15)),
                ('streetAddress1', models.CharField(blank=True, default='', max_length=200)),
                ('streetAddress2', models.CharField(blank=True, default='', max_length=200)),
                ('city', models.CharField(blank=True, default='', max_length=200)),
                ('state', models.CharField(blank=True, default='', max_length=200)),
                ('postal', models.CharField(blank=True, default='', max_length=200)),
                ('country', models.CharField(blank=True, default='', max_length=200)),
                ('businessId', models.CharField(blank=True, default='', max_length=15)),
                ('discoverUs', models.CharField(blank=True, choices=[('PS', 'Please Select'), ('GS', 'Google Search'), ('A', 'Advertisemant'), ('SM', 'Social Media'), ('O', 'Others (Please specify)')], max_length=200)),
                ('others', models.CharField(blank=True, default='', max_length=200)),
                ('active', models.BooleanField(default=True, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
