# Generated by Django 4.2 on 2023-04-08 15:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('laundApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyregisterform',
            name='acctLevel',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='companyregisterform',
            name='joinDate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companyregisterform',
            name='lastLogin',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
