# Generated by Django 4.2 on 2023-04-09 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laundApp', '0002_companyregisterform_acctlevel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyregisterform',
            name='discoverUs',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
