# Generated by Django 4.2 on 2023-04-09 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laundApp', '0003_alter_companyregisterform_discoverus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyregisterform',
            name='businessId',
            field=models.CharField(blank=True, default='', max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='companyregisterform',
            name='businessName',
            field=models.CharField(default='', max_length=200, unique=True),
        ),
    ]
