# Generated by Django 4.2 on 2023-04-12 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laundApp', '0004_alter_companyregisterform_businessid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyregisterform',
            name='otpConfirm',
            field=models.BooleanField(default=False),
        ),
    ]
