# Generated by Django 4.2 on 2023-04-13 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laundApp', '0005_companyregisterform_otpconfirm'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyregisterform',
            name='termsCondition',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
