# Generated by Django 4.2 on 2023-04-19 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laundApp', '0008_alter_services_updateddate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='updatedDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='companyregisterform',
            name='lastLogin',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='services',
            name='updatedDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
