# Generated by Django 4.2 on 2023-04-19 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('laundApp', '0010_services_createdby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='comProfileField',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='laundApp.companyregisterform'),
        ),
        migrations.AlterField(
            model_name='services',
            name='categoryId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='laundApp.category'),
        ),
        migrations.AlterField(
            model_name='services',
            name='comProfileField',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='laundApp.companyregisterform'),
        ),
    ]
