# Generated by Django 4.2 on 2023-05-06 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laundApp', '0011_alter_category_comprofilefield_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='iconId',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
    ]
